### ISSUE TITLE
Retake de_ancient bomb is planted in the sky

### ISSUE THREAD

**Issue by lopustp** [b3none/retakes-autoplant#12]
So on Ancient bomb is getting planted in the sky on B bombsite any idea why? I don't know if this script is even maintained anymore and I don't know if the problem is in this script..?

**Comment by B3none** [comment]
This will be down to your spawns, double check it's definitely on the ground. If it is then this issue is with the project code.

**Comment by mgeerse** [comment]
> 
> 
> This will be down to your spawns, double check it's definitely on the ground. If it is then this issue is with the project code.

I have the same problem as OP, and the problem does seem to lie in your plugin somewhere. I've tripple checked my retakes spawnpoint but the bomb is getting planted under the ground on de_ancient's bombsite B. Disabling your plugin and allowing for manual plant works fine.

But then I'd probably make the suggestion to OP to update his autoplant plugin, as your latest version 2.3.1 fixes this issue that was present on 2.3.0 just before 👍

**Comment by B3none** [comment]
As this has gone stale I'm going to close it
