### ISSUE TITLE
Not working with [CS:GO] Retakes (not splewis)

### ISSUE THREAD

**Issue by AngATV** [b3none/retakes-autoplant#14]
Hello,

On Cs:Go, i install Splewis Retakes with your plugins and it's perfectly worked.
But on the Retakes from Sourcemod (https://forums.alliedmods.net/showthread.php?t=251829) it's not working.

Followed your steps (I tried with the .smx and compile the .sp with spider) , no erreur inlogs, plugins loaded but not working :(

Any idea/help please ?

**Comment by B3none** [comment]
Turns out you were using Ofir's retakes not splewis retakes. Fix now implemented
