### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Hyden59** [b3none/retakes-autoplant#4]
Hello sorry to bother you, the plugins works to half it is planting the bomb automatically lol but spawn t and not on the site bomb yet the spawn are set on the server

**Comment by B3none** [comment]
It sounds like you're using this plugin on an executes server. Are you aware this is for Retakes?

**Comment by Hyden59** [comment]
Yeah, I have the retake plugins

**Comment by Hyden59** [comment]
Yeah I have the plugins retakes, and the auto plant runs spawn t and not on the bomb site
