### ISSUE TITLE
Bomb Planting

### ISSUE THREAD

**Issue by AleCTC** [b3none/retakes-autoplant#5]
**Describe the bug**
Adding custom coordinates using cl_showpos 1 in the retake by splewis (https://github.com/splewis/csgo-retakes), makes the bomb plant in the air.

**To Reproduce**
Just add a custom location using the command mentioned above, and the plant from the autoplant will end up above the player on the new position.

**Additional context**
Would be nice if the bomb could fall to the ground by itself.

**Comment by B3none** [comment]
This has been a bug for a while! I'll see about looking into it, would you be able to test updates I make?

It might be worth testing a few more solutions such as -
https://forums.alliedmods.net/showpost.php?p=2239502&postcount=2

**Comment by AleCTC** [comment]
Sure thing, add me on steam if you need the help to be quick.
https://steamcommunity.com/id/Koga73/

**Comment by B3none** [comment]
Here's a test branch - https://github.com/b3none/retakes-autoplant/blob/ground-bomb/scripting/retakes_autoplant.sp

**Comment by B3none** [comment]
fixed by #6
